---
server:
  http_listen_port: 3100

limits_config:
   reject_old_samples: true
   reject_old_samples_max_age: 168h
   retention_period: 360h
   max_query_series: 100000
   max_query_parallelism: 2

memberlist:
  join_members:
    - loki:7946

# MINIO S3
schema_config:
  configs:
    - from: 2021-08-01
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: index_
        period: 24h
common:
  path_prefix: /loki
  replication_factor: 1
  storage:
    s3:
      endpoint: minio:9000
      insecure: true
      bucketnames: loki-data
      access_key_id: loki
      secret_access_key: supersecret
      s3forcepathstyle: true
  ring:
    kvstore:
      store: memberlist
ruler:
  storage:
    s3:
      bucketnames: loki-ruler


# Cassandra settings
# storage_config:
#   cassandra:
#     addresses: <comma-separated-IPs-or-hostnames>
#     keyspace: <keyspace>
#     auth: <true|false>
#     username: <username> # only applicable when auth=true
#     password: <password> # only applicable when auth=true

# schema_config:
#   configs:
#     - from: 2020-07-01
#       store: cassandra
#       object_store: cassandra
#       schema: v11
#       index:
#         prefix: index_
#         period: 168h
#       chunks:
#         prefix: chunk_
#         period: 168h

